# Generated by Django 4.1.7 on 2023-04-26 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='accessibility_needs',
            field=models.CharField(choices=[('No Accessibility Requirement', 'No Accessibility Requirement'), ('Wheelchair Accessible Place', 'Wheelchair Accessible Place'), ('Vision Impaired', 'Vision Impaired')], default='No Accessibility Requirement', max_length=100),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='dietary_restrictions',
            field=models.CharField(choices=[('No Dietary Restriction', 'No Dietary Restriction'), ('Halal Restaurants', 'Halal Restaurants'), ('Vegan Restaurants', 'Vegan Restaurants'), ('Kosher Restaurants', 'Kosher Restaurants')], default='No Dietary Restriction', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accessibility_needs',
            field=models.CharField(blank=True, choices=[('No Accessibility Requirement', 'No Accessibility Requirement'), ('Wheelchair Accessible Place', 'Wheelchair Accessible Place'), ('Vision Impaired', 'Vision Impaired')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(blank=True, choices=[('No Dietary Restriction', 'No Dietary Restriction'), ('Halal Restaurants', 'Halal Restaurants'), ('Vegan Restaurants', 'Vegan Restaurants'), ('Kosher Restaurants', 'Kosher Restaurants')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PastTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('itinerary_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
