# Generated by Django 4.1.7 on 2023-04-26 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_alter_itinerary_accessibility_needs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastTrip',
            new_name='PreviousTrip',
        ),
    ]
