# Generated by Django 4.1.7 on 2023-05-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_pasttrip_previoustrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='budget',
        ),
    ]
