# Generated by Django 4.1.7 on 2023-05-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_itinerary_dietary_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='accessibility_needs',
            field=models.CharField(choices=[('No Accessibility Requirement', 'No Accessibility Requirement'), ('Wheelchair', 'Wheelchair'), ('Vision-impaired', 'Vision-impaired')], default='No Accessibility Requirement', max_length=100),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='dietary_restrictions',
            field=models.CharField(choices=[('No Dietary Restriction', 'No Dietary Restriction'), ('Halal Restaurants', 'Halal Restaurants'), ('Vegan', 'Vegan'), ('Kosher', 'Kosher')], default='No Dietary Restriction', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accessibility_needs',
            field=models.CharField(blank=True, choices=[('No Accessibility Requirement', 'No Accessibility Requirement'), ('Wheelchair', 'Wheelchair'), ('Vision-impaired', 'Vision-impaired')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(blank=True, choices=[('No Dietary Restriction', 'No Dietary Restriction'), ('Halal Restaurants', 'Halal Restaurants'), ('Vegan', 'Vegan'), ('Kosher', 'Kosher')], max_length=100, null=True),
        ),
    ]
