# Generated by Django 4.1.7 on 2023-05-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_itinerary_accessibility_needs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='dietary_restrictions',
            field=models.CharField(choices=[('No Dietary Restriction', 'No Dietary Restriction'), ('Halal', 'Halal'), ('Vegan', 'Vegan'), ('Kosher', 'Kosher')], default='No Dietary Restriction', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(blank=True, choices=[('No Dietary Restriction', 'No Dietary Restriction'), ('Halal', 'Halal'), ('Vegan', 'Vegan'), ('Kosher', 'Kosher')], max_length=100, null=True),
        ),
    ]
